@endpoint=http://localhost:3000/yoga-studio-management-api/v1/book

# @name bookClass
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
    "userId": "6798c605d874f33c7e04ae4b",
    "classId": "673ccbe8f9abce235ff2d3b8"
}
###