# Base URL for the API
@endpoint=http://localhost:3000/yoga-studio-management-api/v1/classlocations

# 1. POST - Create a Class Location (Valid)
# @name postValidClassLocation
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "City Center Yoga Studio",
  "maxCapacity": 30,
  "location": "456 Yoga Plaza, City Center",
  "classFormats": ["Location", "Stream"]
}
###
# Capture the location header from the response to get the ID of the newly created class location
@ClassLocationID = {{postValidClassLocation.response.headers.location}}

# 2. POST - Create a Class Location (Stream Only)
# @name postStreamOnlyClassLocation
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Online Yoga Studio",
  "maxCapacity": 1000,
  "location": "Virtual",
  "classFormats": ["Stream"]
}
###

# 3. GET - Retrieve Class Location by ID (Using ID from POST response)
# @name GetClassLocationByID
GET {{endpoint}}/{{ClassLocationID}} HTTP/1.1
###

# 4. GET - Retrieve All Class Locations (Without Pagination)
# @name GetAllClassLocations
GET {{endpoint}} HTTP/1.1
Content-Type: application/json
###

# 5. GET - Retrieve All Class Locations with Pagination (Page 1, 10 per page)
# @name GetPaginatedClassLocations
GET {{endpoint}}?page=1&pageSize=1
Content-Type: application/json
###

# 6. GET - Retrieve All Class Locations That Support Virtual (Stream) Classes
# @name GetClassLocationsWithVirtualFormat
GET {{endpoint}}?filter={"classFormats":"Stream"} HTTP/1.1
Content-Type: application/json
###

# 7. PUT - Update a Class Location (Update Class Formats to Both)
# @name UpdateClassLocationFormats
PUT {{endpoint}}/{{ClassLocationID}} HTTP/1.1
Content-Type: application/json

{
  "classFormats": ["Both"]
}
###

# 8. DELETE - Delete Class Location by ID (Using ID from POST response)
# @name DeleteClassLocation
DELETE {{endpoint}}/{{ClassLocationID}}HTTP/1.1
Content-Type: application/json
###
