# Base URL for the API
@endpoint=http://localhost:3000/yoga-studio-management-api/v1/instructors

# 1. POST - Create an Instructor (Invalid Email)
# @name postAnInstructorInvalidEmail
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Rois Shannon",
  "yogaSpecialities": ["Hatha", "Vinyasa"],
  "email": "invalid-email" 
}
###

# 2. POST - Create an Instructor (Empty Yoga Specialities)
# @name postAnInstructorWithEmptyYogaSpecialities
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Alice Smith",
  "yogaSpecialities": [],   
  "email": "alice.smith@example.com"
}
###

# 3. POST - Create an Instructor (Invalid Yoga Speciality)
# @name postAnInstructorWithInvalidYogaSpeciality
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "yogaSpecialities": ["InvalidYogaType"], 
  "email": "jane.doe@example.com"
}
###

# 4. POST - Create a Valid Instructor (Success) --> testing one to many relationship
# @name postValidInstructor
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Testing Relationship",
  "yogaSpecialities": ["Ashtanga", "Bikram"],
  "email": "john.doe@example.com"
}
###

# Capture the location header from the response to get the ID of the newly created instructor
@InstructorID = {{postValidInstructor.response.headers.location}}

# 5. GET - Retrieve Instructor by ID (Using InstructorID from POST response)
GET {{endpoint}}/{{InstructorID}} HTTP/1.1
###

# 6. GET - Retrieve All Instructors
# @name GetAllInstructors
GET {{endpoint}} HTTP/1.1
Content-Type: application/json
###

# 7. DELETE - Delete Instructor by ID (Using InstructorID captured from POST request)
DELETE {{endpoint}}/{{InstructorID}} HTTP/1.1
Content-Type: application/json
###

# 8. Capture the First Instructor's ID from the list of all instructors
@FirstInstructorID = {{GetAllInstructors.response.body.$[0]._id}}

# 9. Update - Update Email and Yoga Specialities of the First Instructor (Using FirstInstructorID)
# @name UpdateInstructorYogaAndEmail
PUT {{endpoint}}/{{FirstInstructorID}} HTTP/1.1
Content-Type: application/json

{
  "yogaSpecialities": ["Bikram", "Kundalini"],
  "email": "updated.email@example.com"
}
###

# 10. GET - Retrieve First Instructor by ID (Using FirstInstructorID)
# @name GetFirstInstructorByID
GET {{endpoint}}/{{FirstInstructorID}} HTTP/1.1
###

# 11. DELETE - Delete the first instructor in the list of all instructors
# @name DeleteFirstInstructor
DELETE {{endpoint}}/{{FirstInstructorID}} HTTP/1.1
Content-Type: application/json
###

# 12. Try to GET a Non-Existent Instructor (Invalid ID)
# @name GetNonExistentInstructor
GET {{endpoint}}/nonexistentID HTTP/1.1
Content-Type: application/json
###

# 13. POST - Create Another Instructor 
# @name postAnotherInstructor
POST {{endpoint}} HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "yogaSpecialities": ["Vinyasa", "Restorative"],
  "email": "jane.doe@example.com"
}
###

# Capture the new instructor ID from the response location header (direct ObjectId)
@AnotherInstructorID = {{postAnotherInstructor.response.headers.location}}

# 14. GET - Retrieve Another Instructor by ID (Using AnotherInstructorID)
# @name GetAnotherInstructorByID
GET {{endpoint}}/{{AnotherInstructorID}} HTTP/1.1
###

# 15. GET - Retrieve all instructors with yoga specialities "Vinyasa"
# @name GetFilteredInstructorsWithVinyasa
GET {{endpoint}}?filter={"yogaSpecialities":"Vinyasa"}
###

# 16. GET - Retrieve all instructors with yoga specialities "Hatha" and "Vinyasa" (both required)
# @name GetInstructorsWithOnlyHathaAndVinyasa
GET {{endpoint}}?filter={"yogaSpecialities":{"$all":["Hatha","Vinyasa"],"$size":2}}
###

# 17. GET - Retrieve all instructors with yoga specialities "Hatha" or "Vinyasa" (either allowed)
# @name GetInstructorsWithEitherHathaOrVinyasa
GET {{endpoint}}?filter={"yogaSpecialities":{"$in":["Hatha","Vinyasa"]}}
###

# 18. GET - Retrieve paginated instructors with page 3 and pageSize 5
# @name GetPaginatedInstructors
GET {{endpoint}}?page=5&pageSize=5
Content-Type: application/json
###

# get classes for an instructor
# @name GetClassesForAnInstructor
GET {{endpoint}}/673b81982ffa0fbbc33f94a5
Content-Type: application/json
###